### ISSUE TITLE
 egcpms_ctl fails to list devices

### ISSUE THREAD

**Issue by psiniemi** [scosu/egpms_ctl#1]
```
$ sudo ./egpms_ctl -l
Traceback (most recent call last):
  File "./egpms_ctl", line 203, in <module>
    gather_devices()
  File "./egpms_ctl", line 140, in gather_devices
    selected_device = usb_dev_map.values()[0]
TypeError: 'dict_values' object does not support indexing
```

I compiled the module for raspberry pi. Controlling the sockets works as I would expect, but I need to get them from sysfs.

Thanks for this btw - it's awesome :)

**Comment by scosu** [comment]
Could you please try again with the latest commit? I am not sure if it has other bugs. However you could also wait for the weekend then I can test it myself with a gembird device ;)

**Comment by psiniemi** [comment]
Thanks, I will. Unfortunately I upgradeded my kernel and the module broke. I need a more robust way of compiling the module so I will do that later this week I hope.

**Comment by psiniemi** [comment]
Set up a couple of jenkins jobs to compile this for my raspberry pi and your fix seems to work. Thank you for the fast response.
